language: generic
env:
  HUGO_VERSION: "0.51"

cache:
  pip: true
  directories:
    - node_modules

install:
  - curl -sSL https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.tar.gz -o /tmp/hugo.tar.gz
  - tar -xzf /tmp/hugo.tar.gz -C $HOME/bin

script:
  - npm install
  - npm run build
  - hugo --minify --baseURL $BASE_URL

deploy:
  - provider: s3
    bucket: $S3_BUCKET_NAME
    region: $S3_BUCKET_REGION
    local_dir: public
    skip_cleanup: true
    acl: public_read
    on:
      branch: master
  - provider: lambda
    function_name: $LAMBDA_FUNC_NAME
    region: $LAMBDA_FUNC_REGION
    runtime: nodejs8.10
    handler_name: handler
    zip: ${TRAVIS_BUILD_DIR}/function
    skip_cleanup: true
    on:
      branch: master

after_deploy:
  - pyenv global system 3.6
  - pip3 install --user awscli
  - aws configure set preview.cloudfront true
  - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
