title: Ce te ține treaz noaptea
languageCode: ro

params:
  by: Code for Romania
  url: https://code4.ro/ro/
  copy: Civic Labs este un program desfășurat de Code for Romania prin care ne dorim diagnosticarea problemelor românilor din țară și de pretutindeni pentru a putea identifica soluții sustenabile și eficiente.
  description: Vrem să știm ce te frământă, cu ce probleme te confrunți, ce ai vrea să meargă mai bine în țară. Semnalează-ne o problemă pe care ai identificat-o, iar noi vom încerca să o analizăm, cercetăm, validăm și apoi să îi găsim soluție.

staticDir:
  - static
  - theme

menu:
  header:
    - name: Despre Civic Labs
      pre: fa fa-code
      url: https://civiclabs.ro/
    - name: Donează
      pre: fab fa-paypal
      url: https://code4.ro/ro/doneaza/
  social:
    - name: facebook
      url: https://www.facebook.com/code4romania/
      weight: 1
    - name: twitter
      url: https://twitter.com/Code4Romania
      weight: 2
    - name: github
      url: https://github.com/code4romania/
      weight: 3
    - name: linkedin
      url: https://www.linkedin.com/company/code4romania/
      weight: 4

blackfriday:
  hrefTargetBlank: true
  fractions: false

googleAnalytics: UA-142069348-1
privacy:
  googleAnalytics:
    anonymizeIP: true
    respectDoNotTrack: true
    useSessionStorage: true

disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
  - sitemap
